CREATE TABLE "public"."User" (
  "id" VARCHAR(25) PRIMARY KEY NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "password" VARCHAR(255) NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL
);

CREATE TABLE "public"."Post" (
  "id" VARCHAR(25) PRIMARY KEY NOT NULL,
  "title" VARCHAR(255) NOT NULL,
  "body" TEXT NOT NULL,
  "published" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL,
  "authorId" VARCHAR(25),
  CONSTRAINT FK_Post_User FOREIGN KEY ("authorId") REFERENCES "public"."User"("id") ON DELETE CASCADE
);

CREATE TABLE "public"."Comment" (
  "id" VARCHAR(25) PRIMARY KEY NOT NULL,
  "text" TEXT NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL,
  "authorId" VARCHAR(25),
  "postId" VARCHAR(25),
  CONSTRAINT FK_Comment_User FOREIGN KEY ("authorId") REFERENCES "public"."User"("id") ON DELETE CASCADE,
  CONSTRAINT FK_Comment_Post FOREIGN KEY ("postId") REFERENCES "public"."Post"("id") ON DELETE CASCADE
);